### ISSUE TITLE
ImportError: No module named zklib

### ISSUE THREAD

**Issue by bigdawgbz** [GauravSahu/hr_biometric_machine#10]
Followed your instructions to install zklib.

But an error occurs when trying to update modules list so as to install the hr_biometric_machine module.

Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 540, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 577, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 313, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 310, in checked_call
    return self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 806, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 406, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 439, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 443, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/odoo-server/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/odoo/odoo-server/openerp/http.py", line 1313, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/odoo-server/addons/hr_biometric_machine/__init__.py", line 1, in <module>
    import biometric_machine
  File "/opt/odoo/odoo-server/addons/hr_biometric_machine/biometric_machine.py", line 3, in <module>
    from zklib import zklib
ImportError: No module named zklib

**Comment by GauravSahu** [comment]
hi 
please install  zklib first in your server
sudo easy_install zklib

**Comment by mohamedkotkat** [comment]
i try your solution not work

**Comment by mohamedkotkat** [comment]
> hi
> please install zklib first in your server
> sudo easy_install zklib
> 
> if you need some help
> contact me on
> email - [gauravsahu19@gmail.com](mailto:gauravsahu19@gmail.com)
> whatsapp - +918090779037

not work same error
