### ISSUE TITLE
relation "hr_attendance" does not exist

### ISSUE THREAD

**Issue by LailaBounacer** [GauravSahu/hr_biometric_machine#11]
Hello,

I´m working on Odoo 8.
When I click on Insall the new module, I get this error message:

Odoo Server Error

Traceback (most recent call last):
  File "/home/laila/git/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/laila/git/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/home/laila/git/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/laila/git/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/laila/git/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/laila/git/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/home/laila/git/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/home/laila/git/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/laila/git/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/laila/git/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/laila/git/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/laila/git/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/laila/git/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/laila/git/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/laila/git/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/laila/git/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/laila/git/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/laila/git/odoo/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/home/laila/git/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/laila/git/odoo/addons/hr_biometric_machine-master/report/daily_attendance.py", line 59, in init
    """)
  File "/home/laila/git/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/laila/git/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "hr_attendance" does not exist
LINE 13:                     hr_attendance 
                             ^

Does it have something to do with a tables update in the version I´m working on?

Thank you.

**Comment by GauravSahu** [comment]
Check hr_attendance module installed?

**Comment by LailaBounacer** [comment]
When I try to install it, I get this error:

ProgrammingError: column "date" does not exist
LINE 6:                     Count(date) as punch, 
                                  ^
HINT:  Perhaps you meant to reference the column "hr_attendance.name".

I think it´s a column that does does not exist in the tabe.

What do you think?

**Comment by GauravSahu** [comment]
Please inherit hr_attendance and add a new field as a date 
then install it

**Comment by LailaBounacer** [comment]
Okey, thank you!

**Comment by LailaBounacer** [comment]
any news?

**Comment by albosta** [comment]
Hi Guarav, Can you share the hr_attendance inherited module with all the added fields " category, emp_code, day... etc

**Comment by rawnag** [comment]
Hello 
Any solution 
I face same problem

**Comment by rawnag** [comment]
Hello 
Any solution 
I face same problem

**Comment by ShrikrishnaPatil** [comment]
In which module i need to inherit hr_attendance and where to add date

**Comment by ShrikrishnaPatil** [comment]
ProgrammingError: column "day" does not exist
LINE 6:                     Count(day) as punch,
