### ISSUE TITLE
Reg : ERror While install  module

### ISSUE THREAD

**Issue by ShrikrishnaPatil** [GauravSahu/hr_biometric_machine#24]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 249, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1496, in __call__
    self.load_addons()
  File "/opt/odoo/openerp/http.py", line 1517, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/addons/hr_biometric_machine/__init__.py", line 2, in <module>
    import biometric_machine
ImportError: No module named biometric_machine

**Comment by rcastro-tyc** [comment]
Hi @ShrikrishnaPatil, it was solved in [c347a4](https://github.com/GauravSahu/hr_biometric_machine/commit/c347a419392a9ebd07d5339329a307ce715a4fe6)
